services:
  thematic_analysis_backend:
    platform: linux/amd64
    container_name: thematic_analysis_backend
    build:
      dockerfile: dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Moscow
    depends_on:
      - elasticsearch
    restart: always

  thematic_analysis_nginx:
    image: nginx:1.25.2-alpine
    container_name: thematic_analysis_nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - thematic_analysis_backend

  elasticsearch:
    image: elasticsearch:7.17.13
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - cluster.name=docker-cluster
      - cluster.routing.allocation.disk.threshold_enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-XX:UseAVX=2 -Xms128m -Xmx1g
    ulimits:
      memlock:
        hard: -1
        soft: -1
    healthcheck:
      interval: 30s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
    restart: always
